/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___QUIVER_MARSHAL_MARSHAL_H__
#define ___QUIVER_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:OBJECT,OBJECT (./quiver-marshallers.list:2) */
extern
void _quiver_marshal_VOID__OBJECT_OBJECT (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);


G_END_DECLS

#endif /* ___QUIVER_MARSHAL_MARSHAL_H__ */
