#ifndef FILE_QUIVER_STOCK_ICONS_H
#define FILE_QUIVER_STOCK_ICONS_H


#define QUIVER_STOCK_APP            GTK_STOCK_FILE //"quiver-icon-app"
#define QUIVER_STOCK_BROWSER        GTK_STOCK_DIRECTORY //"quiver-icon-browser"
#define QUIVER_STOCK_ROTATE_CW      "edit-redo" //GTK_STOCK_REDO //"quiver-icon-rotate-cw"
#define QUIVER_STOCK_ROTATE_CCW     "edit-undo" // GTK_STOCK_UNDO //"quiver-icon-rotate-ccw"
#define QUIVER_STOCK_SLIDESHOW      GTK_STOCK_INDEX //"quiver-icon-slideshow"

#define QUIVER_STOCK_ABOUT           GTK_STOCK_ABOUT


#define QUIVER_STOCK_OK              GTK_STOCK_OK
#define QUIVER_STOCK_CANCEL          GTK_STOCK_CANCEL


#define QUIVER_STOCK_OPEN            GTK_STOCK_OPEN
#define QUIVER_STOCK_SAVE            GTK_STOCK_SAVE
#define QUIVER_STOCK_QUIT            GTK_STOCK_QUIT
#define QUIVER_STOCK_CLOSE           GTK_STOCK_CLOSE

#define QUIVER_STOCK_EDIT            GTK_STOCK_EDIT

#define QUIVER_STOCK_PROPERTIES      GTK_STOCK_PROPERTIES
#define QUIVER_STOCK_PREFERENCES     GTK_STOCK_PREFERENCES
#define QUIVER_STOCK_REFRESH         GTK_STOCK_REFRESH

#define QUIVER_STOCK_ADD             GTK_STOCK_ADD
#define QUIVER_STOCK_REMOVE          GTK_STOCK_REMOVE
#define QUIVER_STOCK_EXECUTE         GTK_STOCK_EXECUTE

#define QUIVER_STOCK_DELETE          GTK_STOCK_DELETE
#define QUIVER_STOCK_GO_UP           GTK_STOCK_GO_UP
#define QUIVER_STOCK_GO_BACK         GTK_STOCK_GO_BACK
#define QUIVER_STOCK_GO_FORWARD      GTK_STOCK_GO_FORWARD
#define QUIVER_STOCK_ZOOM_IN         GTK_STOCK_ZOOM_IN
#define QUIVER_STOCK_ZOOM_OUT        GTK_STOCK_ZOOM_OUT
#if GTK_MAJOR_VERSION > 2 || GTK_MAJOR_VERSION == 2 && GTK_MINOR_VERSION >= 8
#define QUIVER_STOCK_FULLSCREEN      GTK_STOCK_FULLSCREEN
#else
#define QUIVER_STOCK_FULLSCREEN      QUIVER_STOCK_GOTO_TOP
#endif
#define QUIVER_STOCK_DIRECTORY       GTK_STOCK_DIRECTORY
#define QUIVER_STOCK_CUT             GTK_STOCK_CUT
#define QUIVER_STOCK_COPY            GTK_STOCK_COPY
#define QUIVER_STOCK_PASTE           GTK_STOCK_PASTE

#define QUIVER_STOCK_GOTO_TOP        GTK_STOCK_GOTO_TOP
#define QUIVER_STOCK_GOTO_FIRST      GTK_STOCK_GOTO_FIRST
#define QUIVER_STOCK_GOTO_LAST       GTK_STOCK_GOTO_LAST

#define QUIVER_STOCK_ZOOM_100        GTK_STOCK_ZOOM_100
#define QUIVER_STOCK_ZOOM_FIT        GTK_STOCK_ZOOM_FIT

#define QUIVER_STOCK_SORT_DESCENDING GTK_STOCK_SORT_DESCENDING








class QuiverStockIcons
{
public:
	static void Load();		
};

#endif

