#ifndef FILE_QUIVER_UI_H
#define FILE_QUIVER_UI_H

#define QUIVER_ACTION_SLIDESHOW  "SlideShow"
#define QUIVER_ACTION_FULLSCREEN "FullScreen"

#define QUIVER_ACTION_UI_MODE_VIEWER "UIModeViewer"
#define QUIVER_ACTION_UI_MODE_BROWSER "UIModeBrowser"

#define QUIVER_UI_MODE_BROWSER   1
#define QUIVER_UI_MODE_VIEWER    2


#endif
