#ifndef FILE_QUIVER_UI_H
#define FILE_QUIVER_UI_H

#define QUIVER_ACTION_SLIDESHOW  "SlideShow"
#define QUIVER_ACTION_FULLSCREEN "FullScreen"

#define QUIVER_ACTION_UI_MODE_VIEWER "UIModeViewer"
#define QUIVER_ACTION_UI_MODE_BROWSER "UIModeBrowser"

#define QUIVER_UI_MODE_BROWSER   1
#define QUIVER_UI_MODE_VIEWER    2


	
char * quiver_ui_main =
"<ui>"
"	<menubar name='MenubarMain'>"
"		<menu action='MenuFile'>"
"			<menuitem action='FileOpen'/>"
"			<menuitem action='FileOpenFolder'/>"
"			<menuitem action='FileOpenLocation'/>"
"			<separator/>"
"			<menuitem action='FileSave'/>"
"			<separator/>"
"			<placeholder action='FileMenuAdditions' />"
"			<separator/>"
"			<menuitem action='Quit'/>"
"		</menu>"
"		<menu action='MenuEdit'>"
"			<menuitem action='Cut'/>"
"			<menuitem action='Copy'/>"
"			<menuitem action='Paste'/>"
"			<separator/>"
"			<menuitem action='ImageTrash'/>"
"			<separator/>"
"			<menuitem action='Preferences'/>"
"		</menu>"
"		<menu action='MenuView'>"
"			<placeholder name='UIModeItems'/>"
"			<menuitem action='ViewMenubar'/>"
"			<menuitem action='ViewToolbarMain'/>"
"			<menuitem action='ViewProperties'/>"
"			<placeholder name='ViewItems'/>"
"		 	<menuitem action='ViewStatusbar'/>"
"			<separator/>"
"			<menuitem action='FullScreen'/>"
"			<menuitem action='SlideShow'/>"
"			<separator/>"
"			<menu action='MenuZoom'>"
"				<menuitem action='ZoomFit'/>"
"				<menuitem action='Zoom100'/>"
"				<menuitem action='ZoomIn'/>"
"				<menuitem action='ZoomOut'/>"
"			</menu>"
"		</menu>"
"		<menu action='MenuImage'>"
"			<menuitem action='RotateCW'/>"
"			<menuitem action='RotateCCW'/>"
"			<separator/>"
"			<menuitem action='FlipH'/>"
"			<menuitem action='FlipV'/>"
"		</menu>"
"		<menu action='MenuGo'>"
"			<menuitem action='ImagePrevious'/>"
"			<menuitem action='ImageNext'/>"
"			<separator/>"
"			<menuitem action='ImageFirst'/>"
"			<menuitem action='ImageLast'/>"
"		</menu>"
"		<menu action='MenuBookmarks'>"
"			<menuitem action='BookmarksAdd'/>"
"			<menuitem action='BookmarksEdit'/>"
"		</menu>"
"		<menu action='MenuTools'>"
"		</menu>"
"		<menu action='MenuWindow'>"
"		</menu>"
"		<menu action='MenuHelp'>"
"			<menuitem action='About'/>"
"		</menu>"
"	</menubar>"
"	<toolbar name='ToolbarMain'>"
"		<placeholder name='UIModeItems'/>"
"		<placeholder name='NavToolItems'/>"
"		<separator/>"
"		<toolitem action='FullScreen'/>"
"		<separator/>"
"		<toolitem action='SlideShow'/>"
"		<separator/>"
"		<toolitem action='ImageTrash'/>"
"		<separator/>"
"	</toolbar>"
"</ui>";


char *quiver_ui_browser =
"<ui>"
"	<menubar name='MenubarMain'>"
"		<menu action='MenuView'>"
"			<placeholder name='UIModeItems'>"
"				<separator/>"
"				<menuitem action='UIModeViewer'/>"
"				<separator/>"
"			</placeholder>"
"		</menu>"
"	</menubar>"
"	<toolbar name='ToolbarMain'>"
"		<placeholder name='UIModeItems'>"
"			<separator/>"
"			<toolitem action='UIModeViewer'/>"
"			<separator/>"
"		</placeholder>"
"		<placeholder name='NavToolItems'>"
"			<separator/>"
"			<separator/>"
"		</placeholder>"
"	</toolbar>"
"</ui>";


char *quiver_ui_viewer =
"<ui>"
"	<menubar name='MenubarMain'>"
"		<menu action='MenuView'>"
"			<placeholder name='UIModeItems'>"
"				<separator/>"
"				<menuitem action='UIModeBrowser'/>"
"				<separator/>"
"			</placeholder>"
"		</menu>"
"	</menubar>"
"	<toolbar name='ToolbarMain'>"
"		<placeholder name='UIModeItems'>"
"			<separator/>"
"			<toolitem action='UIModeBrowser'/>"
"			<separator/>"
"		</placeholder>"
"		<placeholder name='NavToolItems'>"
"			<separator/>"
"			<toolitem action='ImageFirst'/>"
"			<toolitem action='ImagePrevious'/>"
"			<toolitem action='ImageNext'/>"
"			<toolitem action='ImageLast'/>"
"			<separator/>"
"		</placeholder>"
"	</toolbar>"
"</ui>";

#endif
